version: '3.9'

services:
  investment_manager_web:
    image: investment_manager_web
    build:
      context: .
      dockerfile: src/InvestmentManager.Web/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Docker
    ports:
        - "5000:80"
    depends_on:
      - "sql_server_db"

  sql_server_db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "sql_server_db"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@someThingComplicated1234"
      ACCEPT_EULA: "Y"
 