

services:
  investmentmanager.db:
    container_name: investmentmanager.db
    environment:
        SA_PASSWORD: "@someThingSecret1234"
        ACCEPT_EULA: "Y"
    user: root
    restart: always
    ports:
        - "1433:1433"
    volumes:
        - ./mssql_data:/var/opt/mssql/data
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "@someThingSecret1234" -Q "SELECT 1" -b -o /dev/null
        interval: 15s
        timeout: 3s
        retries: 10

  investmentmanager.web:
    container_name: investmentmanager.web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ApplicationDbContext=Server=investmentmanager.db;Database=InvestmentManagerDB;User Id=SA;Password=@someThingSecret1234;MultipleActiveResultSets=true;TrustServerCertificate=True"
    restart: always
    ports:
      - "5000:80"
    depends_on:
      investmentmanager.db:
        condition: service_healthy