version: '3.4'

services:
  investmentmanager.db:
    image: mcr.microsoft.com/mssql/server:2022-latest

  investmentmanager.web:
    image: ${DOCKER_REGISTRY-}investmentmanagerweb
    build:
      context: .
      dockerfile: src/InvestmentManager.Web/Dockerfile

volumes:
  mssql_data:
